### ISSUE TITLE
Issue while running the music-dl command

### ISSUE THREAD

**Issue by chirag200666** [vishaltelangre/music-dl#11]
Hi I installed npm version 5.5.1 and was trying to use music-dl, but it is throwing error: 

/usr/local/lib/node_modules/music-dl/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/usr/local/lib/node_modules/music-dl/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/music-dl/node_modules/libxmljs/lib/bindings.js:1:99)
    at Module._compile (module.js:570:32)

**Comment by vishaltelangre** [comment]
@chirag200666 Looks like you had installed `music-dl` with a node/npm version and now trying to use with a different version.

Please try reinstalling the `music-dl` package globally using `npm install -g music-dl`.

**Comment by vishaltelangre** [comment]
Closing due to no activity.
