### ISSUE TITLE
Error while trying to uninstall this package

### ISSUE THREAD

**Issue by rbalogic** [vishaltelangre/music-dl#7]
```
Unhandled rejection Error: Argument #2: Expected string but got null lru-cache@^4.0.1 fetched in 158ms
    at addDependency (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:463:5
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by vishaltelangre** [comment]
@balogic Can you please post the exact command which generated this error? 

Also, it will be good to post the version using `music-dl -v`.

**Comment by vishaltelangre** [comment]
I tried to uninstall using the following command, which worked for me.

```
npm uninstall -g music-dl
```

Please let me know if it doesn't work for you.

**Comment by rbalogic** [comment]
@vishaltelangre I have tried with this command
```
$ npm -v
5.0.4

$ music-dl -v
music-dl v0.0.5

$  npm uninstall -g music-dl
Unhandled rejection Error: Argument #2: Expected string but got nullinstall loadIdealTree
    at addDependency (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:515:3)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:463:5
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:35
    at Array.forEach (native)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:52:11
    at Array.forEach (native)
    at asyncMap (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/async-map.js:51:8)
    at loadDeps (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:455:3)
    at Array.<anonymous> (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
    at /home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/and-finish-tracker.js:8:8
    at resolveBranchDeps.then (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/lib/install/deps.js:419:11)
    at tryCatcher (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/balvis/.nvm/versions/node/v6.4.0/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/balvis/.npm/_logs/2017-07-05T05_28_15_665Z-debug.log
```

Here are the logs from the log file
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/balvis/.nvm/versions/node/v6.4.0/bin/node',
1 verbose cli   '/home/balvis/.nvm/versions/node/v6.4.0/bin/npm',
1 verbose cli   'uninstall',
1 verbose cli   '-g',
1 verbose cli   'music-dl' ]
2 info using npm@5.0.4
3 info using node@v6.4.0
4 verbose npm-session 32f78bdb9b18ff47
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly install loadIdealTree
8 silly install cloneCurrentTreeToIdealTree
9 silly install loadShrinkwrap
10 silly uninstall loadAllDepsIntoIdealTree
11 silly install loadAllDepsIntoIdealTree
12 error cb() never called!
13 error This is an error with npm itself. Please report this error at:
14 error <https://github.com/npm/npm/issues>
```

**Comment by vishaltelangre** [comment]
@balogic Thank you for posting the detailed information.

It looks like an issue with the NPM.

- https://github.com/npm/npm/issues/16738
- https://github.com/npm/npm/issues/16665
- https://github.com/npm/npm/issues/16971

[This comment](https://github.com/npm/npm/issues/16738#issuecomment-312960529) says that it'll be fixed in NPM in a day or two.

Meanwhile, maybe you can try re-install and then uninstall it as follows. 

```
npm i -g music-dl
npm uninstall -g music-dl
```

**Comment by rbalogic** [comment]
Done. Thanks
