### ISSUE TITLE
Cannot find ffmpeg

### ISSUE THREAD

**Issue by AmitKKhanchandani** [vishaltelangre/music-dl#9]
`
Downloading: 100.00% events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find ffmpeg
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\fluent-ffmpeg\lib\processor.js:136:22
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\fluent-ffmpeg\lib\capabilities.js:123:9
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\async\dist\async.js:421:16
    at next (C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\async\dist\async.js:5302:29)
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\async\dist\async.js:906:16
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\fluent-ffmpeg\lib\capabilities.js:116:11
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\fluent-ffmpeg\lib\utils.js:223:16
    at F (C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\which\which.js:68:16)
    at E (C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\which\which.js:80:29)
    at C:\Users\Amit K\AppData\Roaming\npm\node_modules\music-dl\node_modules\which\which.js:89:16
`

node version: 8.2.1
npm version: 5.3.0

**Comment by AmitKKhanchandani** [comment]
i fixed that error by installing FFmpeg for Windows & setting it to %path%

but new error coming around now

`Downloading: 100.00% events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\ffmpeg\bin ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`


no idea how to fix this one?
let me know how to resolved it

**Comment by AmitKKhanchandani** [comment]
Finally Fixed 😄 
Here is how to install it

Install Node.js
Download FFmpeg from http://ffmpeg.zeranoe.com/builds/ and extract the files to C:\ffmpeg
Set your System Path Variable to C:\ffmpeg\bin
Open Command Prompt - > npm install -g music-dl
Usage:- https://github.com/vishaltelangre/music-dl#usage

**Comment by vishaltelangre** [comment]
👍
